### ISSUE TITLE
Orgs that have a custom fiscal year cannot deploy the CollectionTests class

### ISSUE THREAD

**Issue by costonb** [amorek/Apex-Opensource-Library#1]
We're using your Collection class in our managed package and include the unit tests for it.  We ran into an issue where a customer couldn't install our package.  Below is the error they were seeing.

```
Variable does not exist: FiscalQuarter
CollectionTest: Variable does not exist: FiscalQuarter
```

We were able to see that it was the unit tests for the Collection class pretty quickly.  After digging a bit deeper we found that they don't have the FiscalQuarter field because they have custom fiscal year turned on.

For a workaround we're going to just remove any of the unit tests that reference that field.  We're hoping you can get a fix in for this, if not we'll continue to work around it.  We were considering using metadata to see if the field exists and only accessing it by string, but we have not yet looked at the code closely enough to see how viable that may be.

**Comment by amorek** [comment]
Hi @costonb,

Apologies for inconvenience, I've pushed fix for this to the repository. 
Let me know if you have any other issues :)

**Comment by costonb** [comment]
Awesome, thanks for such a quick fix!
